version: "3"

services:
  api:
    # Need to update this to automatically use version from variables
    image: openclimatefix/nowcasting_site_api:${API_VERSION}
    environment:
      DB_URL: $DB_URL
      DB_URL_PV: $DB_URL_PV
      ORIGINS: $ORIGINS
    container_name: nowcasting_api
    command: ["poetry", "run", "uvicorn", "pv_site_api.main:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - 80:80
