name: Bump version and auto-release (docker)
on:
  push:
    branches:
      - main

jobs:
  call-run-docker-release:
    uses: openclimatefix/.github/.github/workflows/docker-release.yml@v1.7.2
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    with:
      image_base_name: nowcasting_site_api
      docker_file: infrastructure/Dockerfile
